### ISSUE TITLE
can't download a specific branch

### ISSUE THREAD

**Issue by nukadelic** [Decad/github-downloader#3]
```
$ ./github-downloader.sh https://github.com/Oculus-VR/Unity-Graphics/tree/2021.2/oculus-appsw-particles/com.unity.render-pipelines.core
Exporting https://github.com/Oculus-VR/Unity-Graphics/2021.2/oculus-appsw-particles/com.unity.render-pipelines.core
svn: E170000: URL 'https://github.com/Oculus-VR/Unity-Graphics/2021.2/oculus-appsw-particles/com.unity.render-pipelines.core' doesn't exist
```

**Comment by Decad** [comment]
Unfortunately this is a limitation of the script, it can't handle branches that have / in them as it can't tell from the URL alone what is a branch and what is a directory. The script could be changed to support passing the branch name as a parameter instead of trying to detect it but that's not something I currently have the bandwidth to do. Thanks for the issue and sorry this script couldn't do what you needed it to!

**Comment by MarketingPip** [comment]
@Decad you can use the GitHub action based version of this [GitHub-Downloader-Action: A Github Action to download files / folders from another repo](https://github.com/MarketingPipeline/GitHub-Downloader-Action) to save your bandwidth & perform test's if still needed. Hope this helps!
